#
# Copyright (C) 2023 Renesas Electronics Corporation.
# Copyright (C) 2023 EPAM Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: aos_core_zephyr

  remotes:
    - name: xen-troops
      url-base: https://github.com/xen-troops

    - name: aoscloud
      url-base: https://github.com/aoscloud

    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: xen-troops
      revision: "b1ab929677"
      west-commands: scripts/west-commands.yml

    - name: aos_core_lib_cpp
      remote: aoscloud
      revision: "v0.2.2"

    - name: aos_core_api
      remote: aoscloud
      revision: "v7.2.2"

    - name: zephyr-xenlib
      remote: xen-troops
      revision: "f93f5d6"

    - name: zephyr-optee-client
      remote: xen-troops
      revision: "9e8e574"

    - name: littlefs
      remote: zephyrproject-rtos
      revision: "ca583fd"
      path: modules/fs/littlefs
      groups:
        - fs

    - name: nanopb
      remote: zephyrproject-rtos
      revision: "42fa8b2"
      path: modules/lib/nanopb

    - name: tinycrypt
      remote: zephyrproject-rtos
      revision: "3e9a49d"
      path: modules/crypto/tinycrypt
      groups:
        - crypto
