#
# Copyright (C) 2023 Renesas Electronics Corporation.
# Copyright (C) 2023 EPAM Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# West YAML manifest for Zephyr as Xen Dom0

manifest:
  self:
    path: aos_core_zephyr

  remotes:
    - name: xen-troops
      url-base: https://github.com/xen-troops

    - name: aoscloud
      url-base: https://github.com/aoscloud

    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: xen-troops
      revision: "69c911c737f9b304e135605e62a2e4771b60effb"
      west-commands: scripts/west-commands.yml

    - name: aos_core_lib_cpp
      remote: aoscloud
      revision: "v0.3.0"

    - name: aos_core_api
      remote: aoscloud
      revision: "v7.2.3"

    - name: zephyr-xenlib
      remote: xen-troops
      revision: "f93f5d6b59ce9c39b1a8ef980530dc5ae372c93f"

    - name: zephyr-optee-client
      remote: xen-troops
      revision: "f3f1455ef27fe1092856b17fcb22b331a8a2ad95"

    - name: littlefs
      remote: zephyrproject-rtos
      revision: "408c16a909dd6cf128874a76f21c793798c9e423"
      path: modules/fs/littlefs
      groups:
        - fs

    - name: nanopb
      remote: zephyrproject-rtos
      revision: "42fa8b211e946b90b9d968523fce7b1cfe27617e"
      path: modules/lib/nanopb

    - name: mbedtls
      remote: zephyrproject-rtos
      revision: "6ec4abdcda78dfc47315af568f93e5ad4398dea0"
      path: modules/crypto/mbedtls
      groups:
        - crypto
